language: python

python:
  - "3.6"
  - "3.8"

script:
  - cd src/
  - make unittest
  - make doctest

after_success:
  - pip install coverage
  - pip install codacy-coverage
  - cd src
  - coverage run -m unittest discover
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - rm coverage.xml .coverage
